apiVersion: v1
kind: Service
metadata:
   name: helloworld-v1
spec:
   ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
   selector:
     app: helloworld-v1
   type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: helloworld-v1
   labels:
      app: helloworld-v1
spec:
   replicas: 1
   selector:
      matchLabels:
         app: helloworld-v1
   template:
      metadata:
         labels:
            app: helloworld-v1
      spec:
         containers:
            - name: helloworld-kubernetes
            # replace <image-tag> with your actual image
              image: localhost:5000/hello
              ports:
                - containerPort: 8080